### ISSUE TITLE
DirectoryNotFoundException if the package has no registered views

### ISSUE THREAD

**Issue by molcsab** [laravel-filament/filament#1047]
### Package

filament/filament

### Package Version

v2.7.4

### Laravel Version

v8.77.1

### Livewire Version

2.8.2

### PHP Version

PHP 8.0.13

### Bug description

If an installed Filament package has no views defined, in the log gets filled with a  "local.ERROR: Uncaught Symfony\Component\Finder\Exception\DirectoryNotFoundException ..." error 

### Steps to reproduce

Install the  Althinect/filament-spatie-roles-permissions package.

### Relevant log output

```shell
local.ERROR: Uncaught Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/Users/watoka/code/filament2dev/vendor/althinect/filament-spatie-roles-permissions/src/../resources/views" directory does not exist. in /Users/watoka/code/filament2dev/vendor/symfony/finder/Finder.php:592
Stack trace:
#0 /Users/watoka/code/filament2dev/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(533): Symfony\Component\Finder\Finder->in('/Users/watoka/co...')
#1 Command line code(1): Illuminate\Filesystem\Filesystem->files('/Users/watoka/co...')
#2 Command line code(1): getViews('/Users/watoka/co...', Object(Illuminate\Filesystem\Filesystem), 'filament-spatie...', '::')
#3 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException: The \"/Users/watoka/code/filament2dev/vendor/althinect/filament-spatie-roles-permissions/src/../resources/views\" directory does not exist. in /Users/watoka/code/filament2dev/vendor/symfony/finder/Finder.php:592
Stack trace:
#0 /Users/watoka/code/filament2dev/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(533): Symfony\\Component\\Finder\\Finder->in('/Users/watoka/co...')
#1 Command line code(1): Illuminate\\Filesystem\\Filesystem->files('/Users/watoka/co...')
#2 Command line code(1): getViews('/Users/watoka/co...', Object(Illuminate\\Filesystem\\Filesystem), 'filament-spatie...', '::')
#3 {main}
  thrown at /Users/watoka/code/filament2dev/vendor/symfony/finder/Finder.php:592)
[stacktrace]
#0 {main}
"}
```

**Comment by danharrin** [comment]
Fixed by #1066.
