### ISSUE TITLE
Layout form components - saving form fields to a single relationship not creating a new related record when one does not exist.

### ISSUE THREAD

**Issue by nettsite** [laravel-filament/filament#10622]
### Package

filament/filament

### Package Version

v3.1.33

### Laravel Version

v10.10

### Livewire Version

v3.3.5

### PHP Version

PHP 8.3.1

### Problem description

A new related record (Client) is not created when an Order is added using the relationship() method on a Fieldset form layout component, and an exception is thrown because the client_id column in the orders table may not be null.

### Expected behavior

I expected a new Client record to be created as described in the [documentation](https://filamentphp.com/docs/3.x/panels/resources/relation-managers#layout-form-components---saving-form-fields-to-a-single-relationship): 

_In this example, the title, description and image are automatically loaded from the metadata relationship, and saved again when the form is submitted. **If the metadata record does not exist, it is automatically created**._

### Steps to reproduce

Attempt to create a new Order - leave the Client field blank, and enter the client details (new client) into the fields in the Client Details fieldset. Click "Create"

### Reproduction repository

https://github.com/nettsite/filament-issue

### Relevant log output

```shell
[2024-01-03 10:51:40] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: orders.client_id (Connection: sqlite, SQL: insert into "orders" ("client_id", "delivery_instructions", "updated_at", "created_at") values (?, ?, 2024-01-03 10:51:40, 2024-01-03 10:51:40)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: orders.client_id (Connection: sqlite, SQL: insert into \"orders\" (\"client_id\", \"delivery_instructions\", \"updated_at\", \"created_at\") values (?, ?, 2024-01-03 10:51:40, 2024-01-03 10:51:40)) at /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)
[stacktrace]
#0 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Illuminate\\Database\\Connection->run()
#2 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\\Database\\Connection->statement()
#3 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#4 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3387): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#5 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1968): Illuminate\\Database\\Query\\Builder->insertGetId()
#6 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1333): Illuminate\\Database\\Eloquent\\Builder->__call()
#7 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1298): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#8 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\\Database\\Eloquent\\Model->performInsert()
#9 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1023): Illuminate\\Database\\Eloquent\\Model->save()
#10 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#11 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1022): tap()
#12 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#13 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#14 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\\Database\\Eloquent\\Model->__call()
#15 /home/william/Projects/filament-issue/app/Filament/Resources/OrderResource/Pages/CreateOrder.php(29): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#16 /home/william/Projects/filament-issue/vendor/filament/filament/src/Resources/Pages/CreateRecord.php(87): App\\Filament\\Resources\\OrderResource\\Pages\\CreateOrder->handleRecordCreation()
#17 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Resources\\Pages\\CreateRecord->create()
#18 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#20 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#22 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(456): Livewire\\Wrapped->__call()
#23 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(99): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->callMethods()
#24 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/LivewireManager.php(96): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#25 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(86): Livewire\\LivewireManager->update()
#26 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#27 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#28 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#29 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#30 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#31 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#33 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#35 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#37 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#39 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#40 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#42 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#44 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#46 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#47 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#48 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#49 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#50 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#51 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#53 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#55 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#57 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#59 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#61 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#63 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#65 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#67 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#68 /home/william/Projects/filament-issue/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#69 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#70 {main}

[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: orders.client_id at /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php:580)
[stacktrace]
#0 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): PDOStatement->execute()
#1 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()
#3 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Illuminate\\Database\\Connection->run()
#4 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\\Database\\Connection->statement()
#5 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#6 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3387): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#7 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1968): Illuminate\\Database\\Query\\Builder->insertGetId()
#8 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1333): Illuminate\\Database\\Eloquent\\Builder->__call()
#9 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1298): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#10 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\\Database\\Eloquent\\Model->performInsert()
#11 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1023): Illuminate\\Database\\Eloquent\\Model->save()
#12 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#13 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1022): tap()
#14 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#15 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#16 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\\Database\\Eloquent\\Model->__call()
#17 /home/william/Projects/filament-issue/app/Filament/Resources/OrderResource/Pages/CreateOrder.php(29): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#18 /home/william/Projects/filament-issue/vendor/filament/filament/src/Resources/Pages/CreateRecord.php(87): App\\Filament\\Resources\\OrderResource\\Pages\\CreateOrder->handleRecordCreation()
#19 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Resources\\Pages\\CreateRecord->create()
#20 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#24 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(456): Livewire\\Wrapped->__call()
#25 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(99): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->callMethods()
#26 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/LivewireManager.php(96): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#27 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(86): Livewire\\LivewireManager->update()
#28 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#29 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#30 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#31 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#32 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#33 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#35 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#37 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#39 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#41 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#42 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#44 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#46 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#48 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#49 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#50 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#51 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#52 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#53 /home/william/Projects/filament-issue/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#55 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#57 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#59 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#61 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#63 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#65 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#67 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#69 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#70 /home/william/Projects/filament-issue/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#71 /home/william/Projects/filament-issue/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#72 {main}
"}
```

**Comment by danharrin** [comment]
Currently, Filament saves child relationships after it saves parents. This is because there might be components inside the nested relationship that depend on the value of the parents existing when they are saved.

In this case, there are two ways to fix it:
- Make the foreign key nullable. If the foreign key is nullable, it will work as expected, as the foreign key will be filled straight after the records are both created. There will be no change to the user experience, but your app must adapt if it has a `creating/created/saving/saved` observer method on the model that depends on the child relationship existing.
- Switch it to a HasOne relationship, so the foreign key on the child table is saved after the parent has been created. It does not need to be nullable, as the parent record already exists by the time the child is saved.

**Comment by nettsite** [comment]
Thank you so much!

I have made the foreign key on the Order model (child) nullable, as you suggested, and it works perfectly.

I am a little concerned about data integrity, because it is now being handled outside of the database when a new order is created, or an existing one updated. I like belts and braces. 

I will cross the observer bridge when I come to it. 

It may be useful to add that bit of information to the documentation. 

Changing the relationship in the Order model to HasOne doesn't seem to make a difference. The Client kis the parent in this relationship, a Client hasMany Orders, and an Order belongsTo a Client. I might have hold of the wrong end of the stick here.
