### ISSUE TITLE
ButtonAction throws error when used inside a HasManyRelationManager

### ISSUE THREAD

**Issue by AlexJames-Dev** [laravel-filament/filament#1119]
### Package

filament/filament

### Package Version

v2.7.17

### Laravel Version

v8.77.1

### Livewire Version

v2.6

### PHP Version

PHP 8.1.1

### Bug description

When attempting to add a Tables\Actions\ButtonAction to the header of a table that is inside a has many relationship manager that points to a function inside the same relationship manager file, upon clicking the action button, i get the following error:

<img width="1435" alt="Screenshot 2022-01-03 at 22 19 15" src="https://user-images.githubusercontent.com/43570309/147987368-9b0f3c32-ea77-4fa5-8eb5-a7d54289760f.png">

The code: 

```
protected function getTableHeaderActions(): array
    {
        return array_merge([
            Tables\Actions\ButtonAction::make('mass_assign_users')
                ->action('mass_assign_users'),
        ], parent::getTableHeaderActions());
    }


    public function mass_assign_users()
    {
        $bookingId = $this->getRelationship()->getParent()->id;
        $thisBookingCourse = Booking::find($bookingId)->course_id;
```

### Steps to reproduce

1. Create a two models and an associated Resource.
2. Create a pivot table storing the id for the two models.
3. Create a "HasMany" relationship manager
4. Add the following function: 
`protected function getTableHeaderActions(): array
    {
        return array_merge([
            Tables\Actions\ButtonAction::make('mass_assign_users')
                ->action('mass_assign_users'),
        ], parent::getTableHeaderActions());
    }`
5. Add a function with the action name: public function mass_assign_users() 
6. Click the button on the table 

### Relevant log output

```shell
[2022-01-03 22:22:43] local.ERROR: Filament\Tables\Actions\Action::Filament\Tables\Actions\Concerns\{closure}(): Argument #2 ($record) must be of type Illuminate\Database\Eloquent\Model, null given, called in /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php on line 36 {"userId":1,"exception":"[object] (TypeError(code: 0): Filament\\Tables\\Actions\\Action::Filament\\Tables\\Actions\\Concerns\\{closure}(): Argument #2 ($record) must be of type Illuminate\\Database\\Eloquent\\Model, null given, called in /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php on line 36 at /Users/alexg/Sites/amber-v3/vendor/filament/tables/src/Actions/Concerns/HasAction.php:16)
[stacktrace]
#0 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Tables\\Actions\\Action->Filament\\Tables\\Actions\\Concerns\\{closure}(Object(App\\Filament\\Resources\\BookingResource\\RelationManagers\\RoomsRelationManager), NULL, Array)
#1 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#2 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#3 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#4 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#5 /Users/alexg/Sites/amber-v3/vendor/filament/tables/src/Actions/Action.php(67): Illuminate\\Container\\Container->call(Object(Closure), Array)
#6 /Users/alexg/Sites/amber-v3/vendor/filament/tables/src/Concerns/HasActions.php(45): Filament\\Tables\\Actions\\Action->call(Array)
#7 /Users/alexg/Sites/amber-v3/vendor/filament/tables/src/Concerns/HasActions.php(74): Filament\\Resources\\RelationManagers\\RelationManager->callMountedTableAction()
#8 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Resources\\RelationManagers\\RelationManager->mountTableAction('mass_assign_use...', NULL)
#9 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /Users/alexg/Sites/amber-v3/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array)
#13 /Users/alexg/Sites/amber-v3/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(38): Livewire\\Component->callMethod('mountTableActio...', Array, Object(Closure))
#14 /Users/alexg/Sites/amber-v3/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate(Object(App\\Filament\\Resources\\BookingResource\\RelationManagers\\RoomsRelationManager), Object(Livewire\\Request))
#15 /Users/alexg/Sites/amber-v3/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#16 /Users/alexg/Sites/amber-v3/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle(Array)
#17 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke('filament.resour...')
#18 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Livewire\\Controllers\\HttpConnectionHandler), '__invoke')
#19 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#20 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#21 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#30 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/alexg/Sites/amber-v3/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/alexg/Sites/amber-v3/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/alexg/Sites/amber-v3/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 /Users/alexg/Sites/amber-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#61 /Users/alexg/Sites/amber-v3/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#62 /Users/alexg/.composer/vendor/laravel/valet/server.php(234): require('/Users/alexg/Si...')
#63 {main}
"}
```

**Comment by danharrin** [comment]
Fixed by #1120 - it will be available in the next release once some other PRs have been finalised.
