### ISSUE TITLE
Routes aren't resolved in Laravel 11

### ISSUE THREAD

**Issue by assertchris** [laravel-filament/filament#12118]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

8.3

### Problem description

Routes defined in `web.php` or with the `->routes()` panel configuration are not resolved before links in `->navigationItems()` panel configuration are. This leads to `Route [x] not defined` errors.

### Expected behavior

I expect to be able to define a route in `web.php` (or with `->routes()`, at a push) and be able to link to it from a navigation or menu button.

### Steps to reproduce

- Make a new Laravel 11 app
- Install Filament (default panel setup, following documentation)
- Define a route (either in `web.php` or with the `->routes()` panel configuration method)
- Open admin

### Reproduction repository

https://github.com/assertchris/filament-route-error-reproduction

### Relevant log output

```shell
[2024-03-31 07:55:58] local.ERROR: Route [foo] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [foo] not defined. at /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:477)
[stacktrace]
#0 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(811): Illuminate\\Routing\\UrlGenerator->route('foo', Array, true)
#1 /Users/assertchris/Herd/filament-route-error-reproduction/app/Providers/Filament/AdminPanelProvider.php(59): route('foo')
#2 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/filament/filament/src/PanelProvider.php(15): App\\Providers\\Filament\\AdminPanelProvider->panel(Object(Filament\\Panel))
#3 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(233): Filament\\PanelProvider->Filament\\{closure}()
#4 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/filament/filament/src/Facades/Filament.php(136): value(Object(Closure))
#5 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(1294): Filament\\Facades\\Filament::Filament\\Facades\\{closure}(Object(Filament\\PanelRegistry), Object(Illuminate\\Foundation\\Application))
#6 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(1240): Illuminate\\Container\\Container->fireCallbackArray(Object(Filament\\PanelRegistry), Array)
#7 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Container\\Container->fireResolvingCallbacks('Filament\\\\PanelR...', Object(Filament\\PanelRegistry))
#8 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1026): Illuminate\\Container\\Container->resolve('Filament\\\\PanelR...', Array, true)
#9 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(723): Illuminate\\Foundation\\Application->resolve('Filament\\\\PanelR...', Array)
#10 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\\Container\\Container->make('Filament\\\\PanelR...', Array)
#11 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): Illuminate\\Foundation\\Application->make('Filament\\\\PanelR...', Array)
#12 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/filament/filament/src/FilamentManager.php(49): app('Filament\\\\PanelR...')
#13 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/filament/filament/src/FilamentServiceProvider.php(48): Filament\\FilamentManager->__construct()
#14 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Filament\\FilamentServiceProvider->Filament\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#15 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\\Container\\Container->build(Object(Closure))
#16 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1026): Illuminate\\Container\\Container->resolve('filament', Array, true)
#17 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(723): Illuminate\\Foundation\\Application->resolve('filament', Array)
#18 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\\Container\\Container->make('filament', Array)
#19 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(1446): Illuminate\\Foundation\\Application->make('filament')
#20 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet('filament')
#21 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('filament')
#22 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(351): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#23 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/filament/filament/routes/web.php(13): Illuminate\\Support\\Facades\\Facade::__callStatic('getPanels', Array)
#24 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Routing/Router.php(509): Illuminate\\Support\\ServiceProvider->{closure}(Object(Illuminate\\Routing\\Router))
#25 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Routing/Router.php(465): Illuminate\\Routing\\Router->loadRoutes(Object(Closure))
#26 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(194): Illuminate\\Routing\\Router->group(Array, Object(Closure))
#27 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/filament/filament/routes/web.php(12): Illuminate\\Routing\\RouteRegistrar->group(Object(Closure))
#28 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(159): require('/Users/assertch...')
#29 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/spatie/laravel-package-tools/src/PackageServiceProvider.php(152): Illuminate\\Support\\ServiceProvider->loadRoutesFrom('/Users/assertch...')
#30 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\\LaravelPackageTools\\PackageServiceProvider->boot()
#31 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#33 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#34 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#35 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1099): Illuminate\\Container\\Container->call(Array)
#36 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1080): Illuminate\\Foundation\\Application->bootProvider(Object(Filament\\FilamentServiceProvider))
#37 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Filament\\FilamentServiceProvider), 19)
#38 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1079): array_walk(Array, Object(Closure))
#39 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#40 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(309): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#41 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#42 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#43 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#44 /Users/assertchris/Herd/filament-route-error-reproduction/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1168): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#45 /Users/assertchris/Herd/filament-route-error-reproduction/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#46 /Applications/Herd.app/Contents/Resources/valet/server.php(151): require('/Users/assertch...')
#47 {main}
"}
```

**Comment by danharrin** [comment]
`->navigationItems([])` gets called before the `->routes([])` function gets executed (due to the lifecycle of the panel, it's not really possible to change this), so by the time `route()` is executed the route has not been registered *yet*.

The fix is simple, defer the route generation by wrapping the route generation in a function, so it only gets executed when the URL is requested to render the sidebar: `->url(fn (): string => route('foo'))`
