### ISSUE TITLE
KeyValue Component should work with any key

### ISSUE THREAD

**Issue by DirtyRacer1337** [laravel-filament/filament#12116]
### Package

filamentphp/forms

### Package Version

v3.2.61

### Laravel Version

v10.48.4

### Livewire Version

v3.4.9

### PHP Version

PHP 8.3

### Problem description

Can't delete some inputs from Key-Value component

If key looks like `https://admin.test.test`, you can add it, but can't delete then

I think problem in dots, need to escape them

### Expected behavior

Record should be deleted

### Steps to reproduce

1. Save record with key `https://admin.test.test`
2. Try to delete it

### Reproduction repository

https://github.com/filamentphp/forms

### Relevant log output

```shell
Filament\Forms\Components\KeyValue::Filament\Forms\Components\{closure}(): Argument #1 ($value) must be of type ?string, array given
```

**Comment by lancepioch** [comment]
FYI this is still an issue. The reason is that the key string is converted directly object access notation when sent over via Livewire. If your component is called "comp" and you have the KeyValue column called "keva" and your key is named "example" with a value of "true...yes", it will normally do `comp.keva.example = "true...yes"` - however if you have a "." in your key name (`example.com`), instead it will do `comp.keva.example.com = "true...yes"`. I'm sure you can see where the problem is. This will cause a failure in the KeyValue component because it's looking for the Key's to be strings, but this casts it to an "array".

However you can easily bypass this issue for now and just add `->live()` to your KeyValue component and Livewire's binding will appropriately cast `example.com` to a string `"example.com"`.

@danharrin in case you want to reopen this one, I can confirm it's an issue in the latest Filament version

**Comment by horaceho** [comment]
> FYI this is still an issue. The reason is that the key string is converted directly object access notation when sent over via Livewire. If your component is called "comp" and you have the KeyValue column called "keva" and your key is named "example" with a value of "true...yes", it will normally do `comp.keva.example = "true...yes"` - however if you have a "." in your key name (`example.com`), instead it will do `comp.keva.example.com = "true...yes"`. I'm sure you can see where the problem is. This will cause a failure in the KeyValue component because it's looking for the Key's to be strings, but this casts it to an "array".
> 
> However you can easily bypass this issue for now and just add `->live()` to your KeyValue component and Livewire's binding will appropriately cast `example.com` to a string `"example.com"`.
> 
> @danharrin in case you want to reopen this one, I can confirm it's an issue in the latest Filament version

Adding `->live()` will generate another error:
```
[2024-07-10 21:07:38] local.ERROR: No synthesizer found for key: "" {"userId":2,"exception":"[object] (Exception(code: 0): No synthesizer found for key: \"\" at /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php:498)
[stacktrace]
#0 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(486): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->getSynthesizerByKey()
#1 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(392): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->propertySynth()
#2 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(408): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->recursivelySetValue()
#3 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(408): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->recursivelySetValue()
#4 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(329): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->recursivelySetValue()
#5 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(300): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->updateProperty()
#6 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(98): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->updateProperties()
#7 /var/www/example.com/code/vendor/livewire/livewire/src/LivewireManager.php(97): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#8 /var/www/example.com/code/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(93): Livewire\\LivewireManager->update()
#9 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#10 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#11 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
#12 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#13 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#16 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#20 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#22 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#23 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#25 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#27 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#29 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#30 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#31 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#32 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#33 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#34 /var/www/example.com/code/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#36 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#38 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#40 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#42 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#46 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#48 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#50 /var/www/example.com/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#51 /var/www/example.com/code/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#52 {main}
"} 
```

**Comment by jmarkfen** [comment]
```php
Forms\Components\KeyValue::make('keyvalues')
    ->editableKeys(false)
    ->dehydrateStateUsing(fn ($state) => Arr::dot($state))
```
