### ISSUE TITLE
Form Components Unable to Handle Nested Relationships Through Polymorphic Connections

### ISSUE THREAD

**Issue by clarkewing** [laravel-filament/filament#14883]
### Package

filament/forms

### Package Version

v3.2.124

### Laravel Version

v11.33.2

### Livewire Version

v3.5.12

### PHP Version

PHP 8.2.26

### Problem description

When attempting to use Form components (Repeater, Group) with nested relationships through a polymorphic connection, Filament tries to access the nested relationship directly on the parent model rather than through the polymorphic relationship chain.

```php
class Chapter extends Model
{
   public function content(): MorphTo
   {
       return $this->morphTo();
   }
}

class LiveTraffic extends Model
{
   public function tracks(): HasMany
   {
       return $this->hasMany(LiveTrafficTrack::class);
   }

   public function chapter(): MorphOne
   {
       return $this->morphOne(Chapter::class, 'content');
   }
}

// In Form
Group::make()
   ->relationship('content')
   ->schema([
       Repeater::make('tracks')
           ->relationship('tracks')
           ->schema([...])
   ])
```

Behavior observed:
```log
BadMethodCallException
Call to undefined method App\Models\Chapter::tracks()
```

### Expected behavior

Form should access tracks through the content relationship chain (Chapter->content->tracks).

### Steps to reproduce

1. Have a polymorphic relationship on Model A (`morphTo`)
2. Have a `hasMany` relationship on Model B (the polymorphic target)
3. Try to create a form with repeater for the nested relationship

To reproduce the issue with the reproduction repository, see detailed steps in associated readme.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/clarkewing/filament-polymorphic-relationships-issue

### Relevant log output

```shell
[2024-11-25 17:27:06] local.ERROR: Call to undefined method App\Models\Chapter::tracks() {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\Chapter::tracks() at /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:67)
[stacktrace]
#0 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('tracks')
#1 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2367): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'tracks', Array)
#2 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/forms/src/Components/Repeater.php(1072): Illuminate\\Database\\Eloquent\\Model->__call('tracks', Array)
#3 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/forms/src/Components/Repeater.php(798): Filament\\Forms\\Components\\Repeater->getRelationship()
#4 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/forms/src/Components/Concerns/HasState.php(218): Filament\\Forms\\Components\\Repeater->getChildComponentContainers(true)
#5 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/forms/src/Concerns/HasState.php(203): Filament\\Forms\\Components\\Component->hydrateState(Array, true)
#6 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/forms/src/Components/Concerns/HasState.php(219): Filament\\Forms\\ComponentContainer->hydrateState(Array, true)
#7 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/forms/src/Concerns/HasState.php(203): Filament\\Forms\\Components\\Component->hydrateState(Array, true)
#8 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/forms/src/Concerns/HasState.php(188): Filament\\Forms\\ComponentContainer->hydrateState(Array, true)
#9 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/filament/src/Resources/Pages/CreateRecord.php(71): Filament\\Forms\\ComponentContainer->fill()
#10 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/filament/src/Resources/Pages/CreateRecord.php(57): Filament\\Resources\\Pages\\CreateRecord->fillForm()
#11 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Resources\\Pages\\CreateRecord->mount()
#12 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#14 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array)
#16 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php(134): Livewire\\Wrapped->__call('mount', Array)
#17 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php(20): Livewire\\Features\\SupportLifecycleHooks\\SupportLifecycleHooks->callHook('mount', Array)
#18 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/ComponentHook.php(19): Livewire\\Features\\SupportLifecycleHooks\\SupportLifecycleHooks->mount(Array, false)
#19 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/ComponentHookRegistry.php(45): Livewire\\ComponentHook->callMount(Array, false)
#20 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/EventBus.php(60): Livewire\\ComponentHookRegistry::Livewire\\{closure}(Object(App\\Filament\\Resources\\ChapterResource\\Pages\\CreateChapter), Array, NULL, false)
#21 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/helpers.php(98): Livewire\\EventBus->trigger('mount', Object(App\\Filament\\Resources\\ChapterResource\\Pages\\CreateChapter), Array, NULL, false)
#22 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(50): Livewire\\trigger('mount', Object(App\\Filament\\Resources\\ChapterResource\\Pages\\CreateChapter), Array, NULL, false)
#23 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/LivewireManager.php(73): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->mount('App\\\\Filament\\\\Re...', Array, NULL)
#24 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(17): Livewire\\LivewireManager->mount('App\\\\Filament\\\\Re...', Array)
#25 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Features/SupportPageComponents/SupportPageComponents.php(117): Livewire\\Component->Livewire\\Features\\SupportPageComponents\\{closure}()
#26 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration(Object(Closure))
#27 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Component->__invoke()
#28 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Filament\\Resources\\ChapterResource\\Pages\\CreateChapter), '__invoke')
#29 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#30 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#31 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/filament/src/Http/Middleware/DispatchServingFilamentEvent.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\DispatchServingFilamentEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/filament/src/Http/Middleware/DisableBladeIconComponents.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\DisableBladeIconComponents->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#48 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/filament/filament/src/Http/Middleware/SetUpPanel.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\SetUpPanel->handle(Object(Illuminate\\Http\\Request), Object(Closure), Object(Filament\\Panel))
#55 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#58 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#59 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#60 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#61 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#82 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#83 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#84 /Users/hugo/Developer/filament-polymorphic-relationships-issue/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#85 /Users/hugo/Developer/filament-polymorphic-relationships-issue/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(23): require_once('/Users/hugo/Dev...')
#86 {main}
"}
```

**Comment by clarkewing** [comment]
With lots of iteration and source diving, I am making some progress. So far, I have found it helpful to inform the repeater of the model it is working under:

```php
// In Form
Group::make()
   ->relationship('content')
   ->schema([
       Repeater::make('tracks')
           ->model(LiveTraffic::class)
           ->relationship('tracks')
           ->schema([...])
   ])
```

Now, the form is properly displayed to the user. However, this poses an issue when persisting the data. The `tracks()` relationship isn't saved because filament can't identify which record to use.

Any ideas?

**Comment by clarkewing** [comment]
I **finally** managed to get around the issue. For reference for anyone facing a similar issue, here's what I did.

### Get around the `Repeater` not understanding what model it was working with

For this, I created `BelongsTo` relations on the `Chapter` model for each polymorphic model.

```php
// App\Models\Chapter

public function liveTraffic(): BelongsTo
{
    if ($this->content_type && $this->content_type !== morph_alias(LiveTraffic::class)) {
        throw new Exception('No [liveTraffic] relationship exists on this chapter.');
    }

    return $this->belongsTo(LiveTraffic::class, 'content_id');
}
```

My previous workaround of appending `->model(LiveTraffic::class)` to the `Repeater` object was still problematic for persisting relationships.

### Persist nested relationships

This is what I'd call the _hacky_ part of my workaround. Because nested relationships weren't being persisted by Filament, I had to somehow force its hand while striving for an elegant solution. What I came up with is forcing Filament to keep form components associated with nested relationships **dehydrated**.

```php
// App\Filament\Resources\LessonResource\RelationManagers\ChaptersRelationManager

Group::make()
    ->relationship('liveTraffic')
    ->dehydrated() // This is where the magic happens
    ->schema([
        Repeater::make('tracks')
            ->relationship('tracks')
            ->dehydrated()
            ->schema([
                //
            ]),
    ]),
```

This will ensure the nested relationships are filled when saving the nested models.

However, now I needed to handle saving these nested relationships. For this, I _simply_ overrode the `LiveTraffic` model's `save()` method.

```php
// App\Models\LiveTraffic

public function save(array $options = []): bool
{
    $tracks = collect($this->tracks)?->map(
        fn ($track) => $track instanceof LiveTrafficTrack ? $track->toArray() : $track
    )->all() ?? [];

    unset($this->attributes['tracks']);

    $saved = parent::save($options);

    if ($tracks !== $this->getRelationValue('tracks')) {
        $presentIds = [];

        foreach ($tracks as $trackData) {
            $track = $this->tracks()->findOrNew($trackData['id'] ?? null);

            $track->fill($track->fillableFromArray($trackData));

            $track->save();

            $presentIds[] = $track->id;
        }

        if (! empty($presentIds)) {
            $this->tracks()->whereNotIn('id', $presentIds)->delete();
        }

        $this->load('tracks');
    }

    return $saved;
}
```

Note: if you're using Mass Assignment Protection, remember to add the relationship's name (in this case `tracks`) to your model's `$fillable` array.

At some point, I may wrap this logic in a trait to keep the code cleaner, but for now (and while waiting for a fix), this works!!

**Comment by danharrin** [comment]
I'm visiting this issue because you donated to the project to help find a solution (thank you!). The relationship method on layout components indeed doesn't really support morph relationships properly at the moment, and you're right that somewhere we would need to specify exactly which model you'd want to save to.

It actually looks like there is some bug to do with nesting relationships at the moment, whereby relationship repeaters dont get saved on the Create page if they are embedded within a relationship layout component. The fix for that is probably going to formulate the bulk of my work.

**Comment by danharrin** [comment]
While I can support property specifying a related model in v3 (`relationship('name', relatedModel: RelatedModel::class)`) to fix `MorphTo`, that isn't very useful unless we also fix the creation issue. As far as I can see we can't fix the creation issue without introducing a breaking change in the framework, which will save the `MorphTo` BEFORE the `HasMany` is saved. Unfortunately, this will require `BelongsTo` and `MorphTo` relationships to have nullable foreign keys all the time, due to the order in which Filament is able to save the data.

**Comment by danharrin** [comment]
#16083 implements the changes, I would really appreciate any feedback you have once we release the beta version of v4 with this included!

**Comment by clarkewing** [comment]
Hi Dan,

Thank you so much for looking into this and developing a fix. I'm eager to try it out in v4!

**Comment by denizaygundev** [comment]
For anyone coming across this, and having the problem even without polymorphic connections, and needs a solution that they can implement in v3, this is what I did: 

For example, if we have the following in the same resource: 
`Users` (Resource) > belongsTo `Subscription` (Section relationship) > hasMany `Items` (Repeater relationship)

`Items` will never be populated without a Subscription being created first (separately). 

And `->dehydrated` after the relationship wasn't working for me unfortunately, the data was still unavailable and I found mixed behaviour between the create and edit for some reason.

So on the create I was able to get the nested data for `Items` (so I then had to manually create the `Items` in the `CreateUser.php: afterCreate` but on edit I wasn't as the `Items` was unavailable not matter what combination I tried, luckily on edit as the User already exists, I was then able to just create the `Subscription` upon a field being selected.

@danharrin not sure if your PR fixes this case?
