### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by ipmrlx** [laravel-filament/filament#14923]
### Package

filament/tables

### Package Version

v3.2.126

### Laravel Version

v11.34.2

### Livewire Version

v3.5.12

### PHP Version

PHP 8.3.14

### Problem description

APP_LOCALE=ru
File=/vendor/filament/tables/resources/views/components/selection/indicator.blade.php
Line=52
Error=[2024-11-30 05:22:06] local.ERROR: A non-numeric value encountered (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): A non-numeric value encountered (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) at /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Translation/MessageSelector.php:352)

### Expected behavior

Show table

### Steps to reproduce

1. more than 1000 entries in the table
2. add custom bulk action:
```php
 Tables\Actions\BulkAction::make('syncCategory')
                        ->label('Отправить в категории')
                        ->icon('heroicon-o-tag')
                        ->form([
                            Select::make('category_ids')
                                ->label('Категория')
                                ->multiple()
                                ->options(function () use ($namesSelectArray) {
                                    return $namesSelectArray;
                                })
                                ->optionsLimit(500)
                                ->searchable()
                                ->required(),
                        ])->action(function ($records) use ($table) {
                            $data = $table->getLivewire()->getMountedTableBulkActionForm()->getState();
                            Product::whereIn('id', $records->map->id)->each(function (Product $product) use ($data) {
                                $product->categories()->sync($data['category_ids']);
                            });
                            Notification::make()
                                ->title('Товары успешно перемещены')
                                ->success()
                                ->send();
                        })->modalWidth('sm'),
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/ipmrlx/filament-error

### Relevant log output

```shell
[2024-11-30 05:22:06] local.ERROR: A non-numeric value encountered (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): A non-numeric value encountered (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) (View: /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/tables/resources/views/components/selection/indicator.blade.php) at /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Translation/MessageSelector.php:352)
[stacktrace]
#0 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(58): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(Illuminate\\View\\ViewException), 1)
#1 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(40): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->handleViewException(Object(Illuminate\\View\\ViewException), 1)
#2 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(74): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->evaluatePath('/Users/ipmrlx/D...', Array)
#3 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(16): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/ipmrlx/D...', Array)
#4 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/View/View.php(209): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->get('/Users/ipmrlx/D...', Array)
#5 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/View/View.php(192): Illuminate\\View\\View->getContents()
#6 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/View/View.php(161): Illuminate\\View\\View->renderContents()
#7 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(241): Illuminate\\View\\View->render(Object(Closure))
#8 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(285): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->Livewire\\Mechanisms\\HandleComponents\\{closure}()
#9 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(233): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->trackInRenderStack(Object(App\\Filament\\Resources\\ProductResource\\Pages\\ListProducts), Object(Closure))
#10 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(54): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->render(Object(App\\Filament\\Resources\\ProductResource\\Pages\\ListProducts), '<div></div>')
#11 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/LivewireManager.php(73): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->mount('App\\\\Filament\\\\Re...', Array, NULL)
#12 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/volt/src/LivewireManager.php(23): Livewire\\LivewireManager->mount('App\\\\Filament\\\\Re...', Array, NULL)
#13 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(17): Livewire\\Volt\\LivewireManager->mount('App\\\\Filament\\\\Re...', Array)
#14 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Features/SupportPageComponents/SupportPageComponents.php(117): Livewire\\Component->Livewire\\Features\\SupportPageComponents\\{closure}()
#15 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration(Object(Closure))
#16 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Component->__invoke()
#17 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Route.php(265): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Filament\\Resources\\ProductResource\\Pages\\ListProducts), '__invoke')
#18 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\\Routing\\Route->runController()
#19 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#20 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/filament/src/Http/Middleware/DispatchServingFilamentEvent.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\DispatchServingFilamentEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/filament/src/Http/Middleware/DisableBladeIconComponents.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\DisableBladeIconComponents->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#37 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/ipmrlx/Dev/LOCAL/domina/vendor/filament/filament/src/Http/Middleware/SetUpPanel.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Filament\\Http\\Middleware\\SetUpPanel->handle(Object(Illuminate\\Http\\Request), Object(Closure), Object(Filament\\Panel))
#44 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#47 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#48 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#49 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#50 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/ipmrlx/Dev/LOCAL/domina/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/ipmrlx/Dev/LOCAL/domina/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#73 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#74 /Users/ipmrlx/Dev/LOCAL/domina/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#75 /Users/ipmrlx/Dev/LOCAL/domina/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#76 /Applications/Herd.app/Contents/Resources/valet/server.php(167): require('/Users/ipmrlx/D...')
```

**Comment by danharrin** [comment]
#14924
