### ISSUE TITLE
ERROR  There are no commands defined in the "filament" namespace.

### ISSUE THREAD

**Issue by sahibshakhayev** [laravel-filament/filament#15049]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11.34.2

### PHP Version

8.3.7

### Problem description

Unable to php artisan filament:install returns namespace not found

### Expected behavior

Package not discovering

### Steps to reproduce

Already done:
Added  "Filament\FilamentServiceProvider::class" Service provider to bootstrap/providers.php
Checked composer.json and composer

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/sahibshakhayev/fresh-project

### Relevant log output

```shell
LOG:

[2024-12-10 10:55:23] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 10:59:29] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 10:59:47] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 11:01:26] local.ERROR: Command "make:filament-resource" is not defined.

Did you mean one of these?
    make:cache-table
    make:cast
    make:channel
    make:class
    make:command
    make:component
    make:controller
    make:enum
    make:event
    make:exception
    make:factory
    make:interface
    make:job
    make:job-middleware
    make:listener
    make:mail
    make:middleware
    make:migration
    make:model
    make:notification
    make:notifications-table
    make:observer
    make:policy
    make:provider
    make:queue-batches-table
    make:queue-failed-table
    make:queue-table
    make:request
    make:resource
    make:rule
    make:scope
    make:seeder
    make:session-table
    make:test
    make:trait
    make:view {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"make:filament-resource\" is not defined.

Did you mean one of these?
    make:cache-table
    make:cast
    make:channel
    make:class
    make:command
    make:component
    make:controller
    make:enum
    make:event
    make:exception
    make:factory
    make:interface
    make:job
    make:job-middleware
    make:listener
    make:mail
    make:middleware
    make:migration
    make:model
    make:notification
    make:notifications-table
    make:observer
    make:policy
    make:provider
    make:queue-batches-table
    make:queue-failed-table
    make:queue-table
    make:request
    make:resource
    make:rule
    make:scope
    make:seeder
    make:session-table
    make:test
    make:trait
    make:view at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:726)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('make:filament-r...')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#5 {main}
"} 
[2024-12-10 11:04:14] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 11:12:04] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 11:14:03] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 11:14:11] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 11:14:41] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 11:26:13] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 12:31:50] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 12:39:56] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 12:40:01] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 12:40:50] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"} 
[2024-12-10 12:41:44] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php:660)
[stacktrace]
#0 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(709): Symfony\\Component\\Console\\Application->findNamespace('filament')
#1 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(284): Symfony\\Component\\Console\\Application->find('filament:instal...')
#2 D:\\Projects\\Webcoder\\fresh2\\vendor\\symfony\\console\\Application.php(193): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 D:\\Projects\\Webcoder\\fresh2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1205): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 D:\\Projects\\Webcoder\\fresh2\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#6 {main}
"}
```

**Comment by danharrin** [comment]
I downloaded your reproduction repository and ran the command without issue. I think there must be a cache issue on your side.
