### ISSUE TITLE
Fresh Install 404 /admin with laravel 9

### ISSUE THREAD

**Issue by tech62** [laravel-filament/filament#2660]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

^9.11

### Livewire Version

^2.10

### PHP Version

php8.1.2

### Bug description

After creating a new project with Laragon, and follow the documentation to install filament, i've got a 404 error when i try to go to the /admin route.

I've try to change the domain in the filament configuration and .env file, no effect and running a php artisan optimize after each operation.

I can show the filament routes when i ask` php artisan route:list`

### Steps to reproduce

Create a project with Laragon
composer update
composer require filament/filament
php artisan make:filament-user
php artisan optimize
Go to the projecturl/admin and 404

### Relevant log output
```
[2022-06-04 09:43:49] laravel.WARNING: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\laragon\www\garage\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php on line 403  
[2022-06-04 09:43:49] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:207)
[stacktrace]
#0 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(132): Illuminate\\Log\\LogManager->resolve('deprecations', NULL)
#1 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(119): Illuminate\\Log\\LogManager->get('deprecations')
#2 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(108): Illuminate\\Log\\LogManager->driver('deprecations')
#3 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(122): Illuminate\\Log\\LogManager->channel('deprecations')
#4 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecationError('str_replace(): ...', 'C:\\\\laragon\\\\www\\\\...', 403, 8192)
#5 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'str_replace(): ...', 'C:\\\\laragon\\\\www\\\\...', 403)
#6 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(8192, 'str_replace(): ...', 'C:\\\\laragon\\\\www\\\\...', 403)
#7 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\RouteListCommand.php(403): str_replace('   ', ' \\xE2\\x80\\xBA ', NULL)
#8 [internal function]: Illuminate\\Foundation\\Console\\RouteListCommand->Illuminate\\Foundation\\Console\\{closure}(Array, 13)
#9 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php(558): array_map(Object(Closure), Array, Array)
#10 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(723): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#11 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\RouteListCommand.php(405): Illuminate\\Support\\Collection->map(Object(Closure))
#12 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\RouteListCommand.php(198): Illuminate\\Foundation\\Console\\RouteListCommand->forCli(Object(Illuminate\\Support\\Collection))
#13 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\RouteListCommand.php(114): Illuminate\\Foundation\\Console\\RouteListCommand->displayRoutes(Object(Illuminate\\Support\\Collection))
#14 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Foundation\\Console\\RouteListCommand->handle()
#15 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#20 C:\\laragon\\www\\garage\\vendor\\symfony\\console\\Command\\Command.php(308): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 C:\\laragon\\www\\garage\\vendor\\symfony\\console\\Application.php(998): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 C:\\laragon\\www\\garage\\vendor\\symfony\\console\\Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\RouteListCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 C:\\laragon\\www\\garage\\vendor\\symfony\\console\\Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 C:\\laragon\\www\\garage\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 C:\\laragon\\www\\garage\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"} 
[2022-06-04 09:43:49] laravel.WARNING: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\laragon\www\garage\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php on line 403  

```

**Comment by tech62** [comment]
Just adding `RewriteEngine on` in the Vhost configuration file fixed the problem
