### ISSUE TITLE
Cannot edit pivot data in belongs to many relationships unless they allow duplicates

### ISSUE THREAD

**Issue by coleshirley** [laravel-filament/filament#2827]
### Package

filament/tables

### Package Version

2.13.6

### Laravel Version

9.17.0

### Livewire Version

2.10.5

### PHP Version

8.1.3

### Bug description

When using a relation manager with a belongs to many relationship I added a pivot data form field to the attach form and the edit forms. When attaching a record I can fill in this pivot field normally and the data is populated correctly. However when I edit a already existing record in the table I am unable to change the pivot field because an error is thrown.

This occurs because when filament retrieves the table record it uses `->find()` on the eloquent query which does not retrieve the pivot model. (see https://github.com/laravel-filament/filament/blob/7631c722e04aed33c82bd57fdbabe9ef7a69718c/packages/tables/src/Concerns/HasRecords.php#L60)

If you allow duplicates on the relation manager then there is a separate case that uses `->first()` 

### Steps to reproduce

See my demo repo: https://github.com/coleshirley/filament-belongs-to-many-edit

configure the .env file to use the sqlite database in the database/ folder

user: test@example.com
password: password

1. Log in to filament
2. navigate to the teams resource and open the existing team
3. attempt to edit the existing related user role
4. Error occurs

For convenience I added a test2@example.com user in case you want to test attaching a user with a role as well as editing the role 

### Relevant log output

```shell
[2022-06-18 16:00:13] local.ERROR: Call to a member function update() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function update() on null at /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/filament/tables/src/Actions/EditAction.php:57)
[stacktrace]
#0 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Tables\\Actions\\EditAction->Filament\\Tables\\Actions\\{closure}()
#1 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#2 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#3 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#4 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#5 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/filament/support/src/Concerns/EvaluatesClosures.php(21): Illuminate\\Container\\Container->call()
#6 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/filament/support/src/Actions/Concerns/CanCustomizeProcess.php(20): Filament\\Support\\Components\\ViewComponent->evaluate()
#7 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/filament/tables/src/Actions/EditAction.php(64): Filament\\Tables\\Actions\\EditAction->process()
#8 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Tables\\Actions\\EditAction->Filament\\Tables\\Actions\\{closure}()
#9 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#13 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/filament/support/src/Concerns/EvaluatesClosures.php(21): Illuminate\\Container\\Container->call()
#14 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/filament/support/src/Actions/Action.php(21): Filament\\Support\\Components\\ViewComponent->evaluate()
#15 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/filament/tables/src/Concerns/HasActions.php(83): Filament\\Support\\Actions\\Action->call()
#16 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Resources\\RelationManagers\\RelationManager->callMountedTableAction()
#17 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call()
#21 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(38): Livewire\\Component->callMethod()
#22 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate()
#23 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#24 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle()
#25 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#26 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#27 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#28 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#29 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#30 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#32 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#34 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#36 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#38 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#39 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#41 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#43 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#45 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#46 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#47 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#48 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#49 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#50 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#52 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#54 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#56 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#58 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#60 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#62 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#64 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#66 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#67 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#68 /home/cole-shirley/pull-requests/filament-belongs-to-many-edit/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#69 {main}
"}
```

**Comment by danharrin** [comment]
Fixed by #2828
