### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading '__livewire') [repost]

### ISSUE THREAD

**Issue by zhuoyr** [laravel-filament/filament#4807]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

^9.19

### Livewire Version

v2.10.7

### PHP Version

^8.0.2

### Problem description

my repo:
https://github.com/zhuoyr/filamentphp-demo-mini
or just use official demo:
https://demo.filamentphp.com/blog/categories

![1](https://user-images.githubusercontent.com/537901/199711317-e94f1f1a-e284-4a87-9a06-c96ae184126d.png)
![2](https://user-images.githubusercontent.com/537901/199711321-bb7f5486-cad5-4cb5-981e-821f9205fd68.png)
![3](https://user-images.githubusercontent.com/537901/199711330-977128ad-ab9e-4cb0-b10e-c4d91c6bacc1.png)
![4](https://user-images.githubusercontent.com/537901/199711339-253f4536-dde7-451b-9f70-795dba7122db.png)

### Expected behavior

1. How to avoid this mistake?
2. From the filament package or from the livewire package level, how to fix this problem?

### Steps to reproduce

my repo:
https://github.com/zhuoyr/filamentphp-demo-mini
or just use  official demo:
https://demo.filamentphp.com/blog/categories

![1](https://user-images.githubusercontent.com/537901/199711317-e94f1f1a-e284-4a87-9a06-c96ae184126d.png)
![2](https://user-images.githubusercontent.com/537901/199711321-bb7f5486-cad5-4cb5-981e-821f9205fd68.png)
![3](https://user-images.githubusercontent.com/537901/199711330-977128ad-ab9e-4cb0-b10e-c4d91c6bacc1.png)
![4](https://user-images.githubusercontent.com/537901/199711339-253f4536-dde7-451b-9f70-795dba7122db.png)

### Reproduction repository

https://github.com/zhuoyr/filamentphp-demo-mini

### Relevant log output

```shell
module.esm.js:420 Uncaught TypeError: Cannot read properties of null (reading '__livewire')
    at SupportAlpine.js:53:36
    at Object.get (module.esm.js:398:16)
    at Object.get (module.esm.js:308:14)
    at eval (eval at <anonymous> (module.esm.js:471:14), <anonymous>:4:76)
    at module.esm.js:489:21
    at V (module.esm.js:409:12)
    at module.esm.js:2627:17
    at n (module.esm.js:1613:16)
    at Object.effect (module.esm.js:1588:5)
    at r (module.esm.js:48:33)
(anonymous) @ SupportAlpine.js:53
get @ module.esm.js:398
get @ module.esm.js:308
eval @ VM734:4
(anonymous) @ module.esm.js:489
V @ module.esm.js:409
(anonymous) @ module.esm.js:2627
n @ module.esm.js:1613
effect @ module.esm.js:1588
r @ module.esm.js:48
(anonymous) @ module.esm.js:1195
(anonymous) @ module.esm.js:64
(anonymous) @ module.esm.js:2627
n @ module.esm.js:561
(anonymous) @ module.esm.js:566
Ct @ module.esm.js:782
(anonymous) @ module.esm.js:1190
(anonymous) @ module.esm.js:1176
e @ module.esm.js:1200
clone @ module.esm.js:1175
alpinifyElementsForMorphdomV3 @ SupportAlpine.js:294
alpinifyElementsForMorphdom @ SupportAlpine.js:250
onBeforeElUpdated @ index.js:479
callHook @ morphdom.js:35
morphEl @ morphdom.js:199
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
handleNodeAdded @ morphdom.js:155
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
(anonymous) @ morphdom.js:407
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:463
value @ index.js:386
value @ index.js:291
value @ index.js:269
value @ index.js:11
(anonymous) @ index.js:69
setTimeout (async)
Y @ module.esm.js:419
(anonymous) @ module.esm.js:489
Promise.catch (async)
(anonymous) @ module.esm.js:489
V @ module.esm.js:409
(anonymous) @ module.esm.js:2627
n @ module.esm.js:1613
effect @ module.esm.js:1588
r @ module.esm.js:48
(anonymous) @ module.esm.js:1195
(anonymous) @ module.esm.js:64
(anonymous) @ module.esm.js:2627
n @ module.esm.js:561
(anonymous) @ module.esm.js:566
Ct @ module.esm.js:782
(anonymous) @ module.esm.js:1190
(anonymous) @ module.esm.js:1176
e @ module.esm.js:1200
clone @ module.esm.js:1175
alpinifyElementsForMorphdomV3 @ SupportAlpine.js:294
alpinifyElementsForMorphdom @ SupportAlpine.js:250
onBeforeElUpdated @ index.js:479
callHook @ morphdom.js:35
morphEl @ morphdom.js:199
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
handleNodeAdded @ morphdom.js:155
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
(anonymous) @ morphdom.js:407
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:463
value @ index.js:386
value @ index.js:291
value @ index.js:269
value @ index.js:11
(anonymous) @ index.js:69
Promise.then (async)
(anonymous) @ index.js:64
Promise.then (async)
value @ index.js:62
sendMessage @ index.js:242
value @ index.js:252
later @ debounce.js:8
setTimeout (async)
(anonymous) @ debounce.js:12
value @ index.js:225
(anonymous) @ node_initializer.js:243
value @ index.js:582
(anonymous) @ node_initializer.js:201
module.esm.js:420 Uncaught TypeError: Cannot read properties of null (reading '__livewire')
    at SupportAlpine.js:53:36
    at Object.get (module.esm.js:398:16)
    at Object.get (module.esm.js:308:14)
    at eval (eval at <anonymous> (module.esm.js:471:14), <anonymous>:4:76)
    at module.esm.js:489:21
    at V (module.esm.js:409:12)
    at module.esm.js:2627:17
    at n (module.esm.js:1613:16)
    at Object.effect (module.esm.js:1588:5)
    at r (module.esm.js:48:33)
(anonymous) @ SupportAlpine.js:53
get @ module.esm.js:398
get @ module.esm.js:308
eval @ VM735:4
(anonymous) @ module.esm.js:489
V @ module.esm.js:409
(anonymous) @ module.esm.js:2627
n @ module.esm.js:1613
effect @ module.esm.js:1588
r @ module.esm.js:48
(anonymous) @ module.esm.js:1195
(anonymous) @ module.esm.js:64
(anonymous) @ module.esm.js:2627
n @ module.esm.js:561
(anonymous) @ module.esm.js:566
Ct @ module.esm.js:782
(anonymous) @ module.esm.js:1190
(anonymous) @ module.esm.js:1176
e @ module.esm.js:1200
clone @ module.esm.js:1175
alpinifyElementsForMorphdomV3 @ SupportAlpine.js:294
alpinifyElementsForMorphdom @ SupportAlpine.js:250
onBeforeElUpdated @ index.js:479
callHook @ morphdom.js:35
morphEl @ morphdom.js:199
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
handleNodeAdded @ morphdom.js:155
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
(anonymous) @ morphdom.js:407
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:463
value @ index.js:386
value @ index.js:291
value @ index.js:269
value @ index.js:11
(anonymous) @ index.js:69
setTimeout (async)
Y @ module.esm.js:419
(anonymous) @ module.esm.js:489
Promise.catch (async)
(anonymous) @ module.esm.js:489
V @ module.esm.js:409
(anonymous) @ module.esm.js:2627
n @ module.esm.js:1613
effect @ module.esm.js:1588
r @ module.esm.js:48
(anonymous) @ module.esm.js:1195
(anonymous) @ module.esm.js:64
(anonymous) @ module.esm.js:2627
n @ module.esm.js:561
(anonymous) @ module.esm.js:566
Ct @ module.esm.js:782
(anonymous) @ module.esm.js:1190
(anonymous) @ module.esm.js:1176
e @ module.esm.js:1200
clone @ module.esm.js:1175
alpinifyElementsForMorphdomV3 @ SupportAlpine.js:294
alpinifyElementsForMorphdom @ SupportAlpine.js:250
onBeforeElUpdated @ index.js:479
callHook @ morphdom.js:35
morphEl @ morphdom.js:199
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
handleNodeAdded @ morphdom.js:155
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
handleNodeAdded @ morphdom.js:162
(anonymous) @ morphdom.js:407
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:332
morphEl @ morphdom.js:219
(anonymous) @ morphdom.js:463
value @ index.js:386
value @ index.js:291
value @ index.js:269
value @ index.js:11
(anonymous) @ index.js:69
Promise.then (async)
(anonymous) @ index.js:64
Promise.then (async)
value @ index.js:62
sendMessage @ index.js:242
value @ index.js:252
later @ debounce.js:8
setTimeout (async)
(anonymous) @ debounce.js:12
value @ index.js:225
(anonymous) @ node_initializer.js:243
value @ index.js:582
(anonymous) @ node_initializer.js:201
12Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
index.js:40          POST https://demo.filamentphp.com/livewire/message/filament.core.notifications net::ERR_CONNECTION_CLOSED
value @ index.js:40
sendMessage @ index.js:242
value @ index.js:252
later @ debounce.js:8
setTimeout (async)
(anonymous) @ debounce.js:12
value @ index.js:225
(anonymous) @ Polling.js:68
index.js:40          POST https://demo.filamentphp.com/livewire/message/filament.core.notifications net::ERR_CONNECTION_CLOSED
value @ index.js:40
sendMessage @ index.js:242
value @ index.js:252
later @ debounce.js:8
setTimeout (async)
(anonymous) @ debounce.js:12
value @ index.js:225
(anonymous) @ Polling.js:68
```

**Comment by danharrin** [comment]
Does #4764 fix this?

**Comment by zhuoyr** [comment]
> Does #4764 fix this?

Yes. nice!

**Comment by zhuoyr** [comment]
New issue discovered via #4764: same record, different actions will have errors
![1](https://user-images.githubusercontent.com/537901/199883055-f5772b75-9d15-4e87-b2b2-18731b83ce8a.jpg)

**Comment by awcodes** [comment]
This is a known dom diffing issue at the field level. 

We're working on the best way to resolve this.

Thank you for reporting.

**Comment by danharrin** [comment]
Please check again in the latest release

**Comment by zhuoyr** [comment]
> Please check again in the latest release

It is running well now, thank you

**Comment by michabbb** [comment]
i am not sure if i have the same problem, but I explained it here: https://github.com/filamentphp/filament/issues/4131#issuecomment-1408236072
