### ISSUE TITLE
Associate not working with custom relation name

### ISSUE THREAD

**Issue by Walter-Melon** [laravel-filament/filament#5066]
### Package

filament/filament

### Package Version

v2.0

### Laravel Version

v9.41.0

### PHP Version

PHP 8.1.12

### Problem description

When I try to associate items to an group in its relation manager it wants to fetch the relation with Item::itemGroups but the group relation inside my items is a belongs to relation names group.

### Expected behavior

Associate items to a group using the relation manager of the group

### Steps to reproduce

- Create a model (Item) with a belongs to relationship named group
- Create a model (ItemGroup) with a has many relationship name items
- Create a relation manager for the ItemGroup with the relationship names items
- Add the AssociateAction to the relation manager with preloadRecordSelect
- When trying to add a Item to the ItemGroup it will try to access Item::itemGroups

See the reproduction repository for more details

### Reproduction repository

https://github.com/Walter-Melon/filament-example

### Relevant log output

```shell
[2022-11-25 19:56:56] local.ERROR: Call to undefined method App\Models\Item::itemGroups() {"view":{"view":"/var/www/html/vendor/filament/forms/resources/views/components/select.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Call to undefined method App\\Models\\Item::itemGroups() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2321): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(864): Illuminate\\Database\\Eloquent\\Model->__call()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(104): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\Concerns\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(865): Illuminate\\Database\\Eloquent\\Relations\\Relation::noConstraints()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(39): Illuminate\\Database\\Eloquent\\Builder->getRelationWithoutConstraints()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(127): Illuminate\\Database\\Eloquent\\Builder->has()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(195): Illuminate\\Database\\Eloquent\\Builder->doesntHave()
#8 /var/www/html/vendor/filament/tables/src/Actions/AssociateAction.php(214): Illuminate\\Database\\Eloquent\\Builder->whereDoesntHave()
#9 /var/www/html/vendor/filament/tables/src/Actions/AssociateAction.php(226): Filament\\Tables\\Actions\\AssociateAction->Filament\\Tables\\Actions\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Tables\\Actions\\AssociateAction->Filament\\Tables\\Actions\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/filament/support/src/Concerns/EvaluatesClosures.php(21): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/filament/forms/src/Components/Concerns/HasOptions.php(21): Filament\\Support\\Components\\ViewComponent->evaluate()
#17 /var/www/html/vendor/filament/forms/src/Components/Select.php(360): Filament\\Forms\\Components\\Select->getOptions()
#18 /var/www/html/vendor/filament/forms/src/../resources/views/components/select.blade.php(94): Filament\\Forms\\Components\\Select->getOptionsForJs()
#19 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#20 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\ItemGroupResource\\RelationManagers\\ItemsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#21 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(152): Livewire\\LivewireViewCompilerEngine->get()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\\View\\View->getContents()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\\View\\View->renderContents()
#25 /var/www/html/vendor/filament/support/src/Components/ViewComponent.php(104): Illuminate\\View\\View->render()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(116): Filament\\Support\\Components\\ViewComponent->toHtml()
#27 /var/www/html/vendor/filament/forms/src/../resources/views/component-container.blade.php(50): e()
#28 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#29 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\ItemGroupResource\\RelationManagers\\ItemsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#30 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(152): Livewire\\LivewireViewCompilerEngine->get()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\\View\\View->getContents()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\\View\\View->renderContents()
#34 /var/www/html/vendor/filament/support/src/Components/ViewComponent.php(104): Illuminate\\View\\View->render()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(116): Filament\\Support\\Components\\ViewComponent->toHtml()
#36 /var/www/html/vendor/filament/tables/src/../resources/views/index.blade.php(930): e()
#37 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#38 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\ItemGroupResource\\RelationManagers\\ItemsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#39 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(152): Livewire\\LivewireViewCompilerEngine->get()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\\View\\View->getContents()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\\View\\View->renderContents()
#43 /var/www/html/vendor/filament/support/src/Components/ViewComponent.php(104): Illuminate\\View\\View->render()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(116): Filament\\Support\\Components\\ViewComponent->toHtml()
#45 /var/www/html/vendor/filament/filament/src/../resources/views/resources/relation-manager.blade.php(2): e()
#46 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('...')
#47 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Filament\\Resources\\ItemGroupResource\\RelationManagers\\ItemsRelationManager->Livewire\\ComponentConcerns\\{closure}()
#48 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(152): Livewire\\LivewireViewCompilerEngine->get()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\\View\\View->getContents()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\\View\\View->renderContents()
#52 /var/www/html/vendor/livewire/livewire/src/Component.php(235): Illuminate\\View\\View->render()
#53 /var/www/html/vendor/livewire/livewire/src/HydrationMiddleware/RenderView.php(14): Livewire\\Component->output()
#54 /var/www/html/vendor/livewire/livewire/src/LifecycleManager.php(154): Livewire\\HydrationMiddleware\\RenderView::dehydrate()
#55 /var/www/html/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(15): Livewire\\LifecycleManager->dehydrate()
#56 /var/www/html/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Routing\\Route->run()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(728): Illuminate\\Pipeline\\Pipeline->then()
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\\Routing\\Router->runRouteWithinStack()
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRoute()
#79 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->dispatchToRoute()
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#81 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#82 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#84 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#86 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#90 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#91 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#92 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#93 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#94 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#95 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#96 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#97 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#98 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#99 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#100 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#101 {main}
```

**Comment by danharrin** [comment]
Check the Getting Started docs on the Relation Managers page

```
protected static ?string $inverseRelationship = 'group';
```
