### ISSUE TITLE
Custom Action File Upload - Cannot read properties of null (reading '__livewire')

### ISSUE THREAD

**Issue by 199ocero** [laravel-filament/filament#5737]
### Package

filament/filament

### Package Version

v2.0

### Laravel Version

v9.19

### PHP Version

PHP 8.0.27

### Problem description

The problem is that whenever I tried to upload a csv file using my custom ImportService by calling it inside the action() in my FileUpload, it shows the error below:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading '__livewire')
```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57591686/219946350-afada5c1-70c5-4720-84e6-d3d73c4bbab7.png">

Here is my custom action to import CSV:

```
Actions\Action::make('Import Student')
             ->action(fn ($data) => (new ImportService())->import($data['csv']))
                ->form([
                    FileUpload::make('csv')
                        ->acceptedFileTypes(['text/csv', 'application/csv'])
                        ->directory('upload-attachments')
                ])
 ```
 
 My Service:
 
```
<?php

namespace App\Services;

use App\Imports\StudentImport;
use Illuminate\Support\Facades\Storage;

class ImportService
{
    public function import($file)
    {
        $filePath = "public/$file";
        $import = new StudentImport();

        $import->import(storage_path("app/$filePath"));

        Storage::disk('public')->delete($file);
    }
}
```

My Laravel excel import:

```
<?php

namespace App\Imports;

use App\Models\Student;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\SkipsOnFailure;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;

class StudentImport implements ToModel, SkipsOnFailure, WithValidation, WithHeadingRow
{
    use SkipsFailures, Importable;
    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {
        return new Student([
            'lrn' => $row['lrn'],
            'student_no' => $row['student_no'],
            'email' => $row['email'],
            'first_name' => $row['first_name'],
            'middle_name' => $row['middle_name'],
            'last_name' => $row['last_name'],
            'suffix' => $row['suffix'],
            'birthday' => $row['birthday']
        ]);
    }

    public function rules(): array
    {
        return [
            'lrn' => 'required|digits:12|min:12|max:12|unique:students,lrn',
            'student_no' => 'required|unique:students,student_no',
            'email' => 'required|email|unique:students,email',
            'first_name' => 'required|string',
            'middle_name' => 'required|string',
            'last_name' => 'required|string',
            'suffix' => 'nullable|string',
            'birthday' => 'required|date'
        ];
    }
}
```

### Expected behavior

I can upload the file successfully and see the records in my table so I can say that it's sucess.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/57591686/219946489-e49fa0c5-0c98-41e4-9494-e12566d65bdd.png">

### Steps to reproduce

Clone my the Reproduction repository:

```
https://github.com/199ocero/filament-school
```
And just:

```
composer install
```

### Reproduction repository

https://github.com/199ocero/filament-school

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of null (reading '__livewire')
    at SupportAlpine.js:53:36
    at Object.get (module.esm.js:398:16)
    at Object.get (module.esm.js:308:14)
    at getUploadedFileUrlsUsing (eval at r (module.esm.js:471:14), <anonymous>:13:17)
    at Proxy.<anonymous> (module.esm.js:23921:40)
    at c (module.esm.js:2:1)
    at Generator.<anonymous> (module.esm.js:2:1)
    at Generator.next (module.esm.js:2:1)
    at Ic (module.esm.js:2:1)
    at a (module.esm.js:2:1)
```

**Comment by jlambe** [comment]
We're using the `filament/forms` package to generate custom forms on a Laravel application and we meet the exact same issue.

If the form contains a file upload field/component, at submission, the same console error message appears. The file is uploaded but it polutes our sentry log with the same error message.

**Comment by ericmp33** [comment]
Also having this issue. I have a Table component, which has 2 forms (create and edit). In this forms, I upload images.
When I edit a model and I upload and store an image, I get this:
```js
SupportAlpine.js:49 Alpine: Cannot reference "$wire" outside a Livewire component.
(anonymous) @ SupportAlpine.js:49
get @ module.esm.59f83f7d.js:1
get @ module.esm.59f83f7d.js:1
getUploadedFileUrlsUsing @ VM2658:13
getUploadedFileUrls @ module.esm.59f83f7d.js:227
getFiles @ module.esm.59f83f7d.js:227
(anonymous) @ module.esm.59f83f7d.js:227
(anonymous) @ module.esm.59f83f7d.js:5

SupportAlpine.js:53 Uncaught (in promise) TypeError: Cannot read properties of null (reading '__livewire')
    at SupportAlpine.js:53:36
    at Object.get (module.esm.59f83f7d.js:1:4836)
    at Object.get (module.esm.59f83f7d.js:1:3594)
    at getOptionsUsing (eval at <anonymous> (module.esm.59f83f7d.js:5:653), <anonymous>:12:29)
    at Proxy.getOptions (module.esm.59f83f7d.js:294:3695)
    at Proxy.getChoices (module.esm.59f83f7d.js:294:3515)
    at module.esm.59f83f7d.js:294:3135
    at module.esm.59f83f7d.js:5:22761
```

**Comment by danharrin** [comment]
Not much we can do about this, it's an Alpine-Livewire communication bug. We will revisit this thread when Livewire v3 is released to see if it is fixed by the new version.

**Comment by n1crack** [comment]
I'm getting the same error 
I'm using table and form builder components. I have a table that has parent - child relationships. I have created a select box and listed its parents data.  It is working as expected. And it shows no error at first click.

But somehow when I close the modal and open another one , It shows the error below.  


![image](https://user-images.githubusercontent.com/712404/236153516-a3680489-3e3a-4fd4-8074-c237abc24e28.png)

![image](https://user-images.githubusercontent.com/712404/236153656-f9edc56b-ebae-4aca-bea6-d4975985b157.png)

**Comment by chieh12lee** [comment]
Got the same error.

**Comment by danharrin** [comment]
Fixed by Livewire v3.
