### ISSUE TITLE
Error copying files during php artisan filament:install --panels , throws error exception

### ISSUE THREAD

**Issue by pratikkuikel** [laravel-filament/filament#7141]
### Package

filament/filament

### Package Version

v3.0

### Laravel Version

v10.10

### PHP Version

PHP 8.1.10

### Problem description

When attempting to run the command php artisan filament:install --panels, the following error occurs: 

ErrorException: copy(C:\laragon\www\mabs\public\js/filament/forms/components/color-picker.js): Failed to open stream: No such file or directory 
The error originates in the Filesystem.php file of the Laravel framework:

vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:342

It seems that the script is trying to copy the file color-picker.js from the filament/forms directory to the public/js/filament/forms/components directory. However, it fails to find the source file, resulting in the "No such file or directory" error.

Additionally, the stack trace indicates that the error also involves the AssetsCommand.php file in the Filament package:

vendor\filament\support\src\Commands\AssetsCommand.php:71
This suggests that the issue may be related to a missing or misconfigured file in the Filament package or the Filament asset files are not being properly installed during the filament:install --panels command.

### Expected behavior

Expected Result:

The php artisan filament:install --panels command should execute successfully, copying the necessary assets and files to their respective directories without any errors.

### Steps to reproduce

Initialize a new laravel project - laravel new project 
Install filament - composer require filament/filament:"^3.0"

Run the command php artisan filament:install --panels to install Filament panels.

Actual Result:

The command fails with the provided error message, indicating that the file color-picker.js could not be copied due to a "No such file or directory" error.

![image](https://github.com/filamentphp/filament/assets/35728183/37dc5fbc-dab2-4bd4-a818-2b24dac87aa9)

### Reproduction repository

https://github.com/herecomeslucky0145/filament-panel-install

### Relevant log output

```shell
[2023-07-22 04:33:42] local.ERROR: copy(C:\laragon\www\mabs\public\js/filament/forms/components/color-picker.js): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): copy(C:\\laragon\\www\\mabs\\public\\js/filament/forms/components/color-picker.js): Failed to open stream: No such file or directory at C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php:342)
[stacktrace]
#0 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'copy(C:\\\\laragon...', 'C:\\\\laragon\\\\www\\\\...', 342)
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'copy(C:\\\\laragon...', 'C:\\\\laragon\\\\www\\\\...', 342)
#2 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php(342): copy('C:\\\\laragon\\\\www\\\\...', 'C:\\\\laragon\\\\www\\\\...')
#3 C:\\laragon\\www\\mabs\\vendor\\filament\\support\\src\\Commands\\AssetsCommand.php(71): Illuminate\\Filesystem\\Filesystem->copy('C:\\\\laragon\\\\www\\\\...', 'C:\\\\laragon\\\\www\\\\...')
#4 C:\\laragon\\www\\mabs\\vendor\\filament\\support\\src\\Commands\\AssetsCommand.php(28): Filament\\Support\\Commands\\AssetsCommand->copyAsset('C:\\\\laragon\\\\www\\\\...', 'C:\\\\laragon\\\\www\\\\...')
#5 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Filament\\Support\\Commands\\AssetsCommand->handle()
#6 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#8 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(208): Illuminate\\Container\\Container->call(Array)
#11 C:\\laragon\\www\\mabs\\vendor\\symfony\\console\\Command\\Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#12 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(178): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#13 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\CallsCommands.php(68): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#14 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\CallsCommands.php(28): Illuminate\\Console\\Command->runCommand('Filament\\\\Suppor...', Array, Object(Illuminate\\Console\\OutputStyle))
#15 C:\\laragon\\www\\mabs\\vendor\\filament\\support\\src\\Commands\\UpgradeCommand.php(22): Illuminate\\Console\\Command->call('Filament\\\\Suppor...')
#16 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Filament\\Support\\Commands\\UpgradeCommand->handle()
#17 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#19 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(208): Illuminate\\Container\\Container->call(Array)
#22 C:\\laragon\\www\\mabs\\vendor\\symfony\\console\\Command\\Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#23 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(178): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#24 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\CallsCommands.php(68): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#25 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\CallsCommands.php(28): Illuminate\\Console\\Command->runCommand('Filament\\\\Suppor...', Array, Object(Illuminate\\Console\\OutputStyle))
#26 C:\\laragon\\www\\mabs\\vendor\\filament\\support\\src\\Commands\\InstallCommand.php(29): Illuminate\\Console\\Command->call('Filament\\\\Suppor...')
#27 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Filament\\Support\\Commands\\InstallCommand->__invoke()
#28 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#30 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#31 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#32 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(208): Illuminate\\Container\\Container->call(Array)
#33 C:\\laragon\\www\\mabs\\vendor\\symfony\\console\\Command\\Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#34 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(178): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#35 C:\\laragon\\www\\mabs\\vendor\\symfony\\console\\Application.php(1081): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 C:\\laragon\\www\\mabs\\vendor\\symfony\\console\\Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand(Object(Filament\\Support\\Commands\\InstallCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 C:\\laragon\\www\\mabs\\vendor\\symfony\\console\\Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 C:\\laragon\\www\\mabs\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 C:\\laragon\\www\\mabs\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 {main}
"}
```

**Comment by zepfietje** [comment]
Seems to be caused by `/` vs. `\`.
Could you copy over the recent similar fix to all those commands, @danharrin?

**Comment by Ahmad-Fathy** [comment]
Me too .. the same issue

**Comment by danharrin** [comment]
@zepfietje that fix was for AssetsCommand... (#7051)

@Ahmad-Fathy @herecomeslucky0145 what specific Filament version do you have installed? You can check with `php artisan about`

**Comment by pratikkuikel** [comment]
@danharrin v3.0.0-alpha121

**Comment by danharrin** [comment]
Please upgrade to the latest beta version.

**Comment by pratikkuikel** [comment]
@danharrin php artisan filament:upgrade generated the previous error. Ran composer update and it worked like a charm.

**Comment by zepfietje** [comment]
So this issue no longer exists, @herecomeslucky0145?

**Comment by pratikkuikel** [comment]
@zepfietje The same exception occurs on new installation but if I ran composer update on new laravel and filament installation before using command :  php artisan filament:install --panels , the v3.0.0-alpha121 gets upgraded to v3.0.0-beta6 and the command works as expected.
I think it means the problem has been solved.

**Comment by danharrin** [comment]
When you do a new install, try `composer require filament/filament:"^3.0@beta"`
