### ISSUE TITLE
Missing required parameter for edit route redirect after creation error

### ISSUE THREAD

**Issue by aflorea4** [laravel-filament/filament#7592]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

^10.10

### PHP Version

8.2.6

### Problem description

After trying to create a model using the dashboard, the redirect to the edit page of the same model it's not working because it throws an error: 

Missing required parameter for [Route: filament.resources.employment-announcements.edit] [URI: admin/employment-announcements/{record}/edit] [Missing parameter: record].

### Expected behavior

To redirect succesfully to the edit page after the model it's created.

### Steps to reproduce

1. Login to the dashboard using an account (php artisan migrate:fresh --seed, test@example.com & password)
2. Head to the Employment Announcement resource menu
3. Click on create
4. Fill in the form using any data (the pdf file used was: https://www.orimi.com/pdf-test.pdf but I also tested with others)
5. Hit create and then you should get the error
6. After you close the error modal and click again on the Employment Announcement page from the sidebar you will get a "Created" notification.

_______

I ended up into this after I installed laravel, installed filament, installed dbal, created a model, filled up the migration, headed to model and filled up the fillables and the relation to the users table and then I've tried to generate the filament resource using the --generate flag and then went to fill everything in the resource bc the generate didn't do much.

### Reproduction repository

https://github.com/aflorea4/filament-missing-required-parameter-issue/tree/main

### Relevant log output

```shell
[2023-08-09 10:35:07] local.ERROR: Missing required parameter for [Route: filament.resources.employment-announcements.edit] [URI: admin/employment-announcements/{record}/edit] [Missing parameter: record]. {"userId":1,"exception":"[object] (Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameter for [Route: filament.resources.employment-announcements.edit] [URI: admin/employment-announcements/{record}/edit] [Missing parameter: record]. at /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:35)
[stacktrace]
#0 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/RouteUrlGenerator.php(90): Illuminate\\Routing\\Exceptions\\UrlGenerationException::forMissingParameters(Object(Illuminate\\Routing\\Route), Array)
#1 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(490): Illuminate\\Routing\\RouteUrlGenerator->to(Object(Illuminate\\Routing\\Route), Array, true)
#2 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php(464): Illuminate\\Routing\\UrlGenerator->toRoute(Object(Illuminate\\Routing\\Route), Array, true)
#3 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(808): Illuminate\\Routing\\UrlGenerator->route('filament.resour...', Array, true)
#4 /Users/aflorea4/Workspace/filtest/vendor/filament/filament/src/Resources/Resource.php(445): route('filament.resour...', Array, true)
#5 /Users/aflorea4/Workspace/filtest/vendor/filament/filament/src/Resources/Pages/CreateRecord.php(216): Filament\\Resources\\Resource::getUrl('edit', Array)
#6 /Users/aflorea4/Workspace/filtest/vendor/filament/filament/src/Resources/Pages/CreateRecord.php(96): Filament\\Resources\\Pages\\CreateRecord->getRedirectUrl()
#7 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Resources\\Pages\\CreateRecord->create(false)
#8 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /Users/aflorea4/Workspace/filtest/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array)
#12 /Users/aflorea4/Workspace/filtest/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(36): Livewire\\Component->callMethod('create', Array, Object(Closure))
#13 /Users/aflorea4/Workspace/filtest/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate(Object(App\\Filament\\Resources\\EmploymentAnnouncementResource\\Pages\\CreateEmploymentAnnouncement), Object(Livewire\\Request))
#14 /Users/aflorea4/Workspace/filtest/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#15 /Users/aflorea4/Workspace/filtest/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(19): Livewire\\Connection\\ConnectionHandler->handle(Array)
#16 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Controllers\\HttpConnectionHandler->__invoke('app.filament.re...')
#17 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Livewire\\Controllers\\HttpConnectionHandler), '__invoke')
#18 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#19 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#20 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#29 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/aflorea4/Workspace/filtest/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 /Users/aflorea4/Workspace/filtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#58 /Users/aflorea4/Workspace/filtest/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#59 /Users/aflorea4/.composer/vendor/laravel/valet/server.php(110): require('/Users/aflorea4...')
#60 {main}
"}
```

**Comment by awcodes** [comment]
This is not a bug in Filament.

You are extending `Pivot` instead of `Model` on your `EmploymentAnnouncement` model.

**Comment by jimiero** [comment]
@awcodes  @danharrin I'm having the same error on my CreateTeamUser.php

and yes seems to be related with the `class TeamUser extends Pivot`

if I change it to `class TeamUser extends Model` 

Any way to make it work with Pivot also ?

**Comment by danharrin** [comment]
Look at the properties and methods in the Pivot class and trait, override them back to defaults and see which one affects it. Maybe set `$incrementing = true`?

**Comment by RomainMazB** [comment]
Facing this precise issue today with a different use case I would like to share.

I am two "id" columns:
- one basic auto-incrementing `id` for the foreign keys performance
- a second uuid `public_id` column, just for hiding the database "amount of row" in routing

The public_id column is "database-side generated" using uuidv7 function in postgresql.
Here is the migration file:
```php
Schema::create('projects', function (Blueprint $table) {
    $table->id();
    $table->uuid('public_id')->unique()->default(DB::raw('uuidv7()'));
    $table->string('name', 200);
    $table->timestamps();
});
```
And with this "project-feature", I override the Model `getRouteKeyName` method to handle the laravel-routing stuff:
```php
public function getRouteKeyName(): string
{
    return 'public_id';
}
```
It _almost_ works perfectly within Filament, the only issue is the fact that the uuid, which is generated on database, is not "re-fetched" after creation. [Laravel only get the id returned by the database](https://github.com/laravel/framework/blob/fd5b3c648bd0ec27296c191e294a2c4d6c71b100/src/Illuminate/Database/Eloquent/Model.php#L1400-L1402), if there is one.

It means that when you create a new record from the filament Create page, the record is filled with the `id` but not the `public_id` required for the route binding.

To allows this use case, I created a basic trait that I use in all my Create page using this feature:
```php
trait HandlesFilamentCreateCustomRouteKeyNameRedirection
{
    protected function getRedirectUrlParameters(): array
    {
        return [
            'record' => $this->record->newQuery()->whereKey($this->record->getKey())->value($this->record->getRouteKeyName()),
        ];
    }
}
```
