### ISSUE TITLE
FilamentAsset registering Js without path causes problems

### ISSUE THREAD

**Issue by ernoferrari** [laravel-filament/filament#8015]
### Package

Other

### Package Version

v3.0.29

### Laravel Version

v10.19.0

### Livewire Version

v3.0.0-beta.10

### PHP Version

8.2.9

### Problem description

I was running `php artisan filament:upgrade` command.

### Expected behavior

No errors.

### Steps to reproduce

Add to AppServiceProvider class `boot` method:

```
FilamentAsset::register([
    Js::make('script')
        ->html(new HtmlString('<script type="module" src="path/to/script.js"></script>'))
]);
```

and then run `php artisan filament:upgrade`.

Js class' make method do not require second argument (path) but in AssetCommand class it checks is script remote:

```
public function isRemote(): bool
{
    return str($this->getPath())->startsWith(['http://', 'https://', '//']);
}
```

So when path is null (default value for make method's second argument) then this will raise an error because `getPath` method return value is `string`. If I change the Asset class `getPath` method return value to `?string`, then it causes problems in AssetCommand class.

In AssetCommand class the fix could be like changing:
```
if ($asset->isRemote()) {
    continue;
```
to

```
if (!$asset->hasPath() || $asset->isRemote()) {
    continue;
}
```

Would that kind of change affect something else?

### Reproduction repository

https://github.com/ernoferrari/filament-js-bug

### Relevant log output

```shell
Filament\Support\Assets\Asset::getPath(): Return value must be of type string, null returned {"exception":"[object] (TypeError(code: 0): Filament\\Support\\Assets\\Asset::getPath(): Return value must be of type string, null returned at /var/www/html/vendor/filament/support/src/Assets/Asset.php:55)
[stacktrace]
#0 /var/www/html/vendor/filament/support/src/Assets/Asset.php(60): Filament\\Support\\Assets\\Asset->getPath()
#1 /var/www/html/vendor/filament/support/src/Commands/AssetsCommand.php(32): Filament\\Support\\Assets\\Asset->isRemote()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Support\\Commands\\AssetsCommand->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#8 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#12 /var/www/html/vendor/filament/support/src/Commands/UpgradeCommand.php(21): Illuminate\\Console\\Command->call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Support\\Commands\\UpgradeCommand->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#19 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#22 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#25 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
```

**Comment by danharrin** [comment]
Try `Js::make('script', url('path/to/script.js'))->module()`
