### ISSUE TITLE
"Unsupported operand types: string * int" error when pagination limit set to "All"

### ISSUE THREAD

**Issue by nishadpnktdi** [laravel-filament/filament#8482]
### Package

filament/filament

### Package Version

v3.0.48

### Laravel Version

10.23.1

### PHP Version

PHP 8.1.23

### Problem description

![Screenshot from 2023-09-14 11-53-21](https://github.com/filamentphp/filament/assets/12415708/14347f29-2850-4a9c-b7ce-ee8a9dde28ac)

### Expected behavior

Display row index

### Steps to reproduce

Set per page items count to "All" in data table.

### Reproduction repository

https://github.com/nishadpnktdi/filament-pagination-bug

### Relevant log output

```shell
[previous exception] [object] (TypeError(code: 0): Unsupported operand types: string * int at /home/d5n/Desktop/pagination/vendor/filament/tables/src/Columns/TextColumn.php:70)
[stacktrace]
#0 /home/d5n/Desktop/pagination/vendor/filament/support/src/Concerns/EvaluatesClosures.php(35): Filament\\Tables\\Columns\\TextColumn::Filament\\Tables\\Columns\\{closure}()
#1 /home/d5n/Desktop/pagination/vendor/filament/tables/src/Columns/Concerns/HasState.php(65): Filament\\Support\\Components\\Component->evaluate()
#2 /home/d5n/Desktop/pagination/vendor/filament/tables/src/Columns/Concerns/CanBeCopied.php(18): Filament\\Tables\\Columns\\Column->getState()
#3 /home/d5n/Desktop/pagination/storage/framework/views/dc63d82cc15c7517751b56d1864b833b.php(1706): Filament\\Tables\\Columns\\TextColumn->isClickDisabled()
#4 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(37): include('...')
#5 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(38): App\\Filament\\Resources\\CustomerResource\\Pages\\ListCustomers->Livewire\\Mechanisms\\ExtendBlade\\{closure}()
#6 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->evaluatePath()
#7 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(16): Illuminate\\View\\Engines\\CompilerEngine->get()
#8 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->get()
#9 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#10 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#11 /home/d5n/Desktop/pagination/vendor/filament/support/src/Components/ViewComponent.php(128): Illuminate\\View\\View->render()
#12 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Support/helpers.php(117): Filament\\Support\\Components\\ViewComponent->toHtml()
#13 /home/d5n/Desktop/pagination/storage/framework/views/d537b8624b6aaf80e34a09988c916007.php(68): e()
#14 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(37): include('...')
#15 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(38): App\\Filament\\Resources\\CustomerResource\\Pages\\ListCustomers->Livewire\\Mechanisms\\ExtendBlade\\{closure}()
#16 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->evaluatePath()
#17 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(16): Illuminate\\View\\Engines\\CompilerEngine->get()
#18 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->get()
#19 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#20 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#21 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(248): Illuminate\\View\\View->render()
#22 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(289): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->Livewire\\Mechanisms\\HandleComponents\\{closure}()
#23 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(263): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->trackInRenderStack()
#24 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(111): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->render()
#25 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/LivewireManager.php(96): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#26 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(85): Livewire\\LivewireManager->update()
#27 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#28 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#29 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#30 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#31 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#32 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#34 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#36 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#38 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#40 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#41 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#43 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#45 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
#47 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#48 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#49 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#50 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#51 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#52 /home/d5n/Desktop/pagination/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#54 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#56 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#58 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#60 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(89): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#62 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#64 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#66 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#68 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#69 /home/d5n/Desktop/pagination/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#70 /home/d5n/Desktop/pagination/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('...')
#71 {main}
"}
```

**Comment by nishadpnktdi** [comment]
![Screenshot from 2023-09-14 11-53-21](https://github.com/filamentphp/filament/assets/12415708/a216a528-8155-434a-8ca8-02d346aa7877)
